language: ruby
sudo: false
cache: bundler
bundler_args: --without tools
rvm:
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - ruby-head
  - jruby-head
env:
  global:
    - CODECLIMATE_REPO_TOKEN=1b43f2bc46bf75b5ae0a4e0c956990346599bf84178fabec28f35c899947093b
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c6efc69df9417bda7808
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
